version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.8.2
    steps:
      - checkout
      - run:
          name: hello
          command: |
            echo "Hello world"
workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "19 16 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
